name: roqqu_assesment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  delightful_toast: ^1.1.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  get: ^4.7.2
  get_it: ^8.2.0
  hooks_riverpod: ^2.6.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  uuid: ^4.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1
  fl_chart: ^1.1.0
dependency_overrides:
  vector_math: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
